### ISSUE TITLE
Call-site calculation does not fail gracefully when Stack information is unavailable

### ISSUE THREAD

**Issue by arciisine** [dougwilson/nodejs-depd#27] opened 2018-05-25 11:38 UTC
When the number of stack frames in an error is under 3, `depd` does not fail gracefully. I'm working on a framework that cleans up stack traces by hiding lines that are primarily boilerplate.  In this process, this ends up at times with a stack trace that is small enough to cause this scenario.  

Depd is a transitive dependency that I do not control, and so my application will break with imports failing almost seemingly without a pattern. 

I'm happy to submit a PR.  I'm thinking it should continue properly if it cannot retrieve stack information, but with just an unknown location.

**Comment by arciisine** [comment] 2018-05-25 11:44
As an addendum, attempting to use NO_DEPRECATION only seems to affect whether or not something is logged, vs whether or not the information is calculated.  By allowing NO_DEPRECATION to actually bypass the calculation, that would also work for my use case.

**Comment by dougwilson** [comment] 2018-05-25 17:02
Weird, I remember some kind of fix along those lines, but not 100% sure. Is the transitive dependency in your tree the most up-to-date version (just to check in case you're mixing any such fix)? As for the `NO_DEPRECATION`, that's the correct behavior. I think the section on it in the readme does a pretty good job saying it just controls the output to STDERR and nothing else; the events are still emitted on `process`. If you think the readme can be clarified around that that would be cool to do too.

Yea, if you want to make a PR that would be cool, though if you can provide a repo that reproduces the issue first that I can look at, that would help a lot to get direction on the change prior to spending time working on it 👍

**Comment by arciisine** [comment] 2018-06-01 03:00
Let me get a repro to you, and then we an see if a PR is worthwhile.

**Comment by dougwilson** [comment] 2018-08-12 21:05
Closing since I never got a reproduction case or a follow up pull request.

**Closed by dougwilson** 2018-08-12 21:05 UTC
Labels: awaiting more info

**Comment by charandas** [comment] 2018-08-12 21:17
@dougwilson this is happening for me when I am using sequelize with jest (ts-jest), with the special case that the wrapping library calling sequelize is using [esm](https://github.com/standard-things/esm).

I basically had to disable my tests couple weeks ago because of this. I may be able to get you the repro.

Basically, once the stack frames become invalid, sequelize using depd for deprecating things makes sequelize un-usable in my tests.

Can I reopen this when I have the repro ready?

**Comment by dougwilson** [comment] 2018-08-12 21:26
No problem 👍 I cannot confirm that the incorrect usage is causing your particular issue, but it does cause stack trace-related issues since the frame the instance captured may not contain any of the same frames when the function is later called to display a message. It just sounds like that may be the culprit here, but not sure.

**Comment by dougwilson** [comment] 2018-08-12 21:27
P.S. Sorry for confusing you with OP; I use email for everything here, basically read through email and click through the site to respond; this meant your icon was not next to the text as I was reading it (because I read in my email) and as I scrolled by they had the same colors so I incorrectly assumed it was the same user :D

**Comment by charandas** [comment] 2018-08-12 21:30
No problem.

I think in my stack, the failure happens when sequelize tries to call the depd constructor itself while newing it.

When you say the function cannot find stack frames, it sounds to me like it's in the later workflow when depd instance is already constructed.

**Comment by dougwilson** [comment] 2018-08-12 21:37
> When you say the function cannot find stack frames, it sounds to me like it's in the later workflow when depd instance is already constructed.

Ah, yes. Is it possible you can open an new issue and we can continue the discussion there? You can paste the exact error with it's stack that is thrown when your code hits that line you linked to to get started.

**Comment by charandas** [comment] 2018-08-12 21:54
Yes, will do.
